//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcd.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenData
    {
        public int ItemID { get; set; }
        public string Dataset { get; set; }
        public string Title { get; set; }
        public string Location { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string Field4 { get; set; }
        public string Field5 { get; set; }
        public string Field6 { get; set; }
        public string Field7 { get; set; }
        public string Field8 { get; set; }
        public string Field9 { get; set; }
        public string Accessibility { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string ItemURL { get; set; }
        public string IconURL { get; set; }
        public string IconAltText { get; set; }
        public string ExtraData { get; set; }
    }
}
